In [1]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
block_size = 8
batch_size = 4

In [2]:
with open('wizard_of_oz.txt') as file:
    text = file.read()

In [4]:
chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [5]:
vocab_size = len(chars)

In [6]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s : [string_to_int[c] for c in s]
decode = lambda l : ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text),dtype=torch.long)

In [7]:
print(data[:100])

tensor([ 1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26, 49,
         0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,  0,
         0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1, 47,
        33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1, 36,
        25, 38, 28,  1, 39, 30,  1, 39, 50,  9])


In [8]:
## creating Batches
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batches(split):
    data = train_data if split== 'train'else val_data
    ix = torch.randint(len(data) - block_size,(block_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y= x.to(device),y.to(device)
    return x,y

x,y = get_batches('train')
print('inputs')
print(x)
print('targets')
print(y)
    
    

inputs
tensor([[58,  1, 55, 68, 78, 11,  0,  0],
        [ 1, 61, 58, 65, 69,  1, 66, 58],
        [61, 58,  1, 44, 62, 67,  1, 47],
        [58, 57,  1, 28, 68, 71, 68, 73],
        [54, 72,  1, 72, 68,  1, 73, 58],
        [78,  1, 72, 73, 68, 69, 69, 58],
        [ 1, 73, 61, 58, 62, 71,  0, 73],
        [ 1, 71, 62, 57, 58,  1, 62, 67]], device='cuda:0')
targets
tensor([[ 1, 55, 68, 78, 11,  0,  0,  3],
        [61, 58, 65, 69,  1, 66, 58,  1],
        [58,  1, 44, 62, 67,  1, 47, 68],
        [57,  1, 28, 68, 71, 68, 73, 61],
        [72,  1, 72, 68,  1, 73, 58, 71],
        [ 1, 72, 73, 68, 69, 69, 58, 57],
        [73, 61, 58, 62, 71,  0, 73, 61],
        [71, 62, 57, 58,  1, 62, 67,  1]], device='cuda:0')


/home/ksuser/noise/lib/python3.10/site-packages/torch/cuda/__init__.py:611: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
